# Browser
browser=chrome
timeout=30

# Application URLs
practice_url=https://practicetestautomation.com/practice-test-login/
booking_url=https://www.booking.com/
dropdown_url=https://proleed.academy/exercises/selenium/automation-practice-form-with-radio-button-check-boxes-and-drop-down.php
para_bank=https://parabank.parasoft.com/parabank/index.htm
test_store=https://automationteststore.com/