pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn clean test'
            }
        }
    }

    post {
        always {

            publishHTML([
                reportName: 'Test Report',
                reportDir: 'reports',
                reportFiles: 'index.html',
                keepAll: true,
                alwaysLinkToLastBuild: true,  
                allowMissing: false
            ])

            archiveArtifacts artifacts: 'reports/**', fingerprint: true
        }
    }
}
